### ISSUE TITLE
No configuration file 

### ISSUE THREAD

**Issue by safi099** [cloudsecurityalliance/ctpd#1]
2018/10/05 11:23:38 [*] INFO No configuration file was loaded, using defaults.
2018/10/05 11:23:38 [*] INFO Database localhost is running mongodb version 4.0.2 ()
2018/10/05 11:23:38 [*] INFO Starting ctpd at :8080
 **WARNING Malformed, incorrect or missing CTP API token**
Why it is not running properly?

**Comment by CloudSecurityAlliance** [comment]
Without any details like how you installed it or how you ran it we can't do anything. Please feel free to add more details.

**Comment by safi099** [comment]
I installed the mangodb and the go with its proper integration according to the given instructions and then when I run this command.
curl -H "Authorization: Bearer 1234" http://localhost:8080/api/1.0/
I got the error of 
{
"error": "Malformed, incorrect or missing CTP API token"
}
